# https://github.com/whiskerlabs/ansible-python
# https://monkeyswithbuttons.wordpress.com/2014/04/03/multi-os-support-in-ansible/
---
- name: Install bearded-avenger for CentOS
  hosts: all
  sudo: true
  vars:
    app_user: vagrant
    app_runtime_path: '/tmp/cif'
    app_rules_path: '/vagrant/rules'
    app_log_path: '/tmp/cif'
    GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
    development: true
  pre_tasks:
    - name: Add GH token to profile
      lineinfile: dest="/home/{{ app_user }}/.profile" line="GH_TOKEN={{ GH_TOKEN }}"
  roles:
    - { role: centos71-check, tags: role-centos71-check }
    - { role: bearded-avenger, tags: role-bearded-avenger }