---
- include: venv.yml
  tags: venv

- include: github.yml
  tags: github
  when: GH_TOKEN is defined

- name: Create logging path
  file: path="{{ app_log_path }}" state=directory recurse=true mode=0770 owner="{{ app_user }}" group="{{ app_user }}"