sudo: required
dist: trusty
language: python
python:
    - 2.7
#    - 3.4

before_install:
    - pip install 'setuptools>=18.5'

script:
    - py.test --cov=cif --cov-fail-under=35

notifications:
    email:
        on_success: never
        on_failure: never
