language: python
python:
    - 2.7
    - 3.3

before_install:
    - pip install pyzmq --install-option="--zmq=bundled"

script:
    - python setup.py build
    - nosetests

notifications:
    email:
        on_success: never
        on_failure: never
branches:
    only:
        - master
        - develop
