language: python
python:
    - 2.7

before_install:
    - pip install pyzmq --install-option="--zmq=bundled"
    - pip install git+https://github.com/csirtgadgets/py-whiteface-sdk.git

script:
    - python setup.py build
    - nosetests

notifications:
    email:
        on_success: never
        on_failure: never
