---
- name: Add apt HTTPS support
  apt: name=apt-transport-https state=present
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=3600

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - build-essential
    - htop
    - git