---
# for reference in case you want to deploy this way
#- name: Update code
#  git: repo={{ git_url }} dest={{ app_user_home }}/bearded-avenger version={{ git_version }} accept_hostkey=yes
#  register: git
#  become: yes
#  become_user: "{{ app_user }}"

- name: register latest release
  command: curl -s https://api.github.com/repos/csirtgadgets/bearded-avenger/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4
  register: latest_release_url

- name: Pull latest release
  get_url: url={{ latest_release_url }} dest="{{ app_user_home }}/bearded-avenger"

- name: create dest directory
  file: path={{ app_user_home }}/bearded-avenger mode=0770 owner="{{ app_user }}" group="{{ app_user }}" state=directory
  become: yes
  become_user: "{{ app_user }}"