---
# tasks file for ubuntu

- include: check.yml
  tags: configuration

- include: firewall.yml
  tags: configuration

- include: deps.yml
  tags: configuration

- include: python27.yml
  tags: configuration

- include: user.yml
  tags: configuration

- include: paths.yml
  tags: configuration
  when: not development

- include: rules.yml
  tags: configuration
  when: not development

- include: sdist.yml
  tags: package
  when: not development

- include: venv.yml
  tags: development
  when: development

- include: services.yml
  tags: configuration
  when: not development
  notify:
    - service cif-services start