---
- name: Add python repo
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'

- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=3600

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python2.7
    - python-support
    - python-pytest
    - python-pip
    - python-dev
    - virtualenvwrapper
    - python-virtualenv

- name: update pip
  pip: name="{{ item }}" extra_args="--upgrade"
  with_items: [ requests pip ] # requests first, old version conflicts with new pip