---
- name: register mypath
  shell: pwd
  register: mypath

- name: install requirements
  pip: requirements="requirements.txt" chdir="{{ mypath.stdout }}/../../"

- name: build
  command: python setup.py build chdir="{{ mypath.stdout }}/../../"

- name: test
  command: /usr/local/bin/py.test -s chdir="{{ mypath.stdout }}/../../"

- name: install
  command: python setup.py install chdir="{{ mypath.stdout }}/../../"