---
# defaults file for centos
firewall_allowed_tcp_ports:
  - "22"
  - "443"
  - '5000'
firewall_allowed_udp_ports: []
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
firewall_log_dropped_packets: true

development: false

python_tmp: '/tmp/tmp_install_python'
python_version: '2.7.10'

app_user: cif
app_user_home: "/home/{{ app_user }}"
app_runtime_path: "/var/lib/cif"
app_rules_path: "/etc/cif/rules"
app_log_path: "/var/log/cif"
app_src_path: "{{ app_user_home }}/bearded-avenger"

venv: cif
venv_user: vagrant
venv_source_path: '/vagrant'
venv_home: "/home/{{ venv_user }}/"
venv_path: "{{ venv_home }}/.virtualenvs/{{ venv }}"