---
- name: install requirements
  pip: requirements="requirements.txt" chdir="{{ app_src_path }}"

- name: build
  command: python setup.py build chdir="{{ app_src_path }}"

- name: install
  command: python setup.py install chdir="{{ app_src_path }}"
