---
- name: copy init scripts
  copy: src="{{ item }}" dest="/etc/init.d/{{ item }}" mode=0755 backup=yes
  with_items:
    - cif-router
    - cif-smrt
    - cif-httpd
    - cif-storage
    - cif-hunters
    - cif-services

- name: copy supervisord configs
  copy: src="{{ item }}" dest=/etc/cif/ mode=0660 owner="{{ app_user }}" group="{{ app_user }}"
  with_items:
    - cif-router.conf
    - cif-httpd.conf
    - cif-smrt.conf
    - cif-storage.conf
    - cif-hunters.conf

- name: copy /etc/defaults/cif
  copy: src=defaults dest=/etc/default/cif mode=0660 owner="{{ app_user }}" group="{{ app_user }}"
  notify:
    - start cif-services