---
- name: Add python repo
  apt_repository: repo='ppa:maxmind/ppa'

- name: Update apt cache if needed.
  apt: update_cache=yes

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - geoipupdate
    - libgeoip-dev
    - geoip-bin

- name: create geoip update cron
  cron: name="geoip update" user="root" job="/usr/bin/geoipupdate"
        cron_file=geoipupdate month=*

- name: create /etc/geopip.conf
  file: src=GeoIP.conf dest=/etc/GeoIP.conf owner=root group=root mode=0660

- name: create GeoIP path /usr/local/share/GeoIP
  file: path=/usr/local/share/GeoIP state=directory owner=root group=root mode=0660

- name: download geoip database
  get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz dest=/usr/local/share/GeoIP/

- name: decompress geoip database
  command: gzip -f -d /usr/local/share/GeoIP/GeoLite2-City.mmdb.gz