---

- include: check.yml
  tags: configuration

- include: firewall.yml
  tags: configuration

- include: deps.yml
  tags: configuration

- include: user.yml
  tags: configuration

- include: geoip.yml
  tags: configuration