---
# vars file for ubuntu
development: false

is_64bit: "{{ ansible_architecture }}"
is_ubuntu: "{{ ansible_distribution }}"
is_ubuntu_version: "{{ ansible_distribution_version }}"

app_user: cif
app_user_home: "/home/{{ app_user }}"
app_runtime_path: "/var/lib/cif"
app_rules_path: "/etc/cif/rules"
app_log_path: "/var/log/cif"
app_src_path: "{{ app_user_home }}/bearded-avenger"

venv: cif
venv_user: vagrant
venv_source_path: '/vagrant'
venv_path: "/home/{{ venv_user }}/.virtualenvs/{{ venv }}"
