---
- name: Update code
  git: repo={{ git_url }} dest={{ app_user_home }}/bearded-avenger version={{ git_version }} accept_hostkey=yes
  register: git
  become: yes
  become_user: "{{ app_user }}"

- name: install requirements
  pip: requirements="{{ app_user_home }}/bearded-avenger/requirements.txt"
  sudo: true

- name: setup
  shell: python setup.py install chdir="{{ app_user_home }}/bearded-avenger/"
  sudo: true

- name: copy init scripts
  copy: src="{{ item }}" dest="/etc/init.d/{{ item }}" chmod=0755 backup=yes
  with_items:
    - cif-router
    - cif-smrt
    - cif-httpd
    - cif-storage
    - cif-hunters