---
- set_fact: this_release_ts={{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
- set_fact: this_release_path={{ releases_path }}/{{ this_release_ts }}

- name: Create new release dir
  file: path={{ app_path }} state=directory owner={{ app_user }} group={{ app_user }} mode=0770

- name: Update code
  git: repo={{ git_url }} dest={{ this_release_path }} version={{ git_version }} accept_hostkey=yes
  register: git
  become: yes
  become_user: "{{ app_user }}"

- name: Symlink new release
  file: src={{ this_release_path }} dest={{ current_release_path }} state=link force=yes

- name: fix release directory perms
  file: path={{ this_release_path }} state=directory owner={{ app_user }} group={{ app_user }} recurse=yes

- name: Cleanup
  shell: "ls -1t {{ releases_path }}|tail -n +{{ keep_releases + 1 }}|xargs rm -rf"
  args:
    chdir: '{{ releases_path }}'