---
app_user: cif
app_user_home: "/home/{{ app_user }}"
development: False
geoip_userid: 999999
geoip_key: "000000000000"
geoip_products: GeoLite2-City GeoLite2-Country GeoLite-Legacy-IPv6-City GeoLite-Legacy-IPv6-Country 506 517 533