---
- name: register latest release
  shell: "curl https://api.github.com/repos/csirtgadgets/bearded-avenger/releases/latest | grep tarball_url | head -n 1 | cut -d '\"' -f 4"
  register: latest_release_url

- debug: msg="{{ latest_release_url.stdout }}"

# only if there isn't a stable release
- name: register latest pre-release
  shell: "curl -s https://api.github.com/repos/csirtgadgets/bearded-avenger/releases | grep tarball_url | head -n 1 | cut -d '\"' -f 4"
  register: latest_pre_release_url
  when: latest_release_url.stdout == ''

- debug: msg="{{ latest_pre_release_url.stdout }}"

- fail: msg="unable to determine tarball_url"
  when: latest_release_url.stdout == '' and latest_pre_release_url.stdout == ''

- name: install bearded-avenger via pip
  pip: name="{{ latest_release_url.stdout }}"
  when: latest_release_url.stdout != ''

- name: install bearded-avenger pre-relase via pip
  pip: name="{{ latest_pre_release_url.stdout }}"
  when: latest_pre_release_url.stdout != ''