---
# tasks file for bearded-avenger

- include: user.yml
  tags: configuration

- include: paths.yml
  tags: configuration

- include: rules.yml
  tags: configuration

- include: github.yml
  tags: ['github', 'install']
  when: not development and GH_TOKEN == ''

- include: github_with_token.yml
  when: not development and GH_TOKEN != ''
  tags: ['github', 'install']

- include: services.yml
  tags: configuration
  when: not development
  notify:
    - service cif-services start