---
- name: Install bearded-avenger
  hosts: all
  sudo: true
  vars:
    app_runtime_path: '/tmp/cif'
    app_rules_path: '/vagrant/rules'
    app_log_path: '/tmp/cif'
    app_user: vagrant
    GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
    development: true
  pre_tasks:
    - name: Add GH token to profile
      lineinfile: dest="/home/{{ app_user }}/.profile" line="GH_TOKEN={{ GH_TOKEN }}"
  roles:
    - { role: ubuntu-check, tags: role-ubuntu-check }
    - { role: bearded-avenger, tags: role-bearded-avenger }
