---

- include: check.yml
  tags: configuration

- include: firewall.yml
  tags: configuration

- include: deps.yml
  tags: configuration

- include: bind.yml
  tags: ['configuration', 'bind']

- include: user.yml
  tags: configuration

- include: geoip.yml
  tags: configuration