---
# tasks file for centos

- include: user.yml
  tags: configuration

- include: paths.yml
  tags: configuration

- include: rules.yml
  tags: configuration
  when: not development

- include: venv.yml
  tags: development
  when: development

- include: services.yml
  tags: configuration
  when: not development
