---
- name: register latest release using GH_TOKEN
  shell: "curl https://{{ GH_TOKEN }}:x-oauth-basic@api.github.com/repos/csirtgadgets/bearded-avenger/releases/latest | grep tag_name | head -n 1 | cut -d '\"' -f 4"
  register: latest_release

- debug: msg="{{ latest_release.stdout }}"

# only if there isn't a stable release
- name: register latest pre-release
  shell: "curl -s https://{{ GH_TOKEN }}:x-oauth-basic@api.github.com/repos/csirtgadgets/bearded-avenger/releases | grep tag_name | head -n 1 | cut -d '\"' -f 4"
  register: latest_pre_release
  when: latest_release.stdout == ''

- debug: msg="{{ latest_pre_release.stdout }}"

- fail: unable to determine tag
  when: latest_release.stdout == '' and latest_pre_release.stdout == ''

- name: install bearded-avenger via pip
  pip: name="https://{{ GH_TOKEN }}:x-oauth-basic@api.github.com/repos/csirtgadgets/bearded-avenger/tarball/{{ latest_release.stdout }}"
  when: latest_release.stdout != ''

- name: install bearded-avenger pre-relase via pip
  pip: name="https://{{ GH_TOKEN }}:x-oauth-basic@api.github.com/repos/csirtgadgets/bearded-avenger/tarball/{{ latest_pre_release.stdout }}"
  when: latest_pre_release.stdout != ''


- name: install via pip
  pip: name="https://{{ GH_TOKEN }}:x-oauth-basic@api.github.com/repos/csirtgadgets/bearded-avenger/tarball/3.0.0a1"