---
# tasks file for bearded-avenger

- include: user.yml
  tags: configuration
  when: not development

- include: paths.yml
  tags: configuration

- include: rules.yml
  tags: configuration
  when: not development

- include: github.yml
  tags: ['github', 'install']
  when: GH_TOKEN == '' and not development and not ci and not bdist

- include: github_with_token.yml
  when: GH_TOKEN != '' and not development and not ci and not bdist
  tags: ['github', 'install']

- include: sdist.yml
  when: ci or bdist
  tags: sdist

- include: venv.yml
  tags: development
  when: development and not ci

- include: tokens.yml
  tags: tokens

- include: services.yml
  tags: configuration
  when: not development
  notify:
    - service cif-services start