---
- name: setup the rules directory
  file: path="{{ app_rules_path }}/default" state=directory mode=770 owner="{{ app_user }}" group="{{ app_user }}"

- name: copy csirtg-smrt rules
  copy: src="../../rules/" dest="{{ app_rules_path }}" backup=yes owner="{{ app_user }}" group="{{ app_user }}"  mode="u=rw,g=rw,o-rwx"