---
# tasks file for centos
- name: "Check for 64-bit"
  fail: msg="Must be install 64-bit"
  when: is_64bit != "x86_64"
- name: "Check for Centos"
  fail: msg="Must be CentOS, {{ is_centos }}"
  when: is_centos != "CentOS"
- name: "Check for version 7"
  fail: msg="Must be version 7, {{ is_centos_version }}"
  when: (is_centos_version < "7" or is_centos_version >= "8")

- include: firewall.yml

- name: install EPEL
  yum: name=epel-release state=latest

- name: upgrade all packages
  yum: name=* state=latest

- name: install deps
  yum:
    state: present
    pkg: "{{ item }}"
  with_items:
    - htop
    - git
    - "@Development Tools"
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - python-virtualenvwrapper

- include: python27.yml
