---
# tasks file for bearded-avenger-dev
- name: install virtualenvwrapper
  pip: name=virtualenvwrapper

- name: setup virtualenv
  shell: /usr/bin/virtualenv "{{ venv_path }}"
  become: yes
  become_user: "{{ venv_user }}"

- name: update pip
  pip: name="{{ item }}" virtualenv="{{ venv_path }}" extra_args="--upgrade"
  with_items: [ requests pip cython ] # requests first, old version conflicts with new pip
  become: yes
  become_user: "{{ venv_user }}"

- name: install requirements
  pip: requirements="{{ venv_source_path }}/requirements.txt" virtualenv="{{ venv_path }}"
  become_user: "{{ venv_user }}"
  become: yes

- name: install pyinstaller
  pip: name="git+https://github.com/pyinstaller/pyinstaller.git@f5c305452cfec603d7bf6940437607567144372a#egg=PyInstaller" virtualenv="{{ venv_path }}"
  become: yes
  become_user: "{{ venv_user }}"

- name: setup develop
  shell: "cd {{ venv_source_path }}; {{ venv_path }}/bin/python setup.py develop"
  become_user: "{{ venv_user }}"
  become: yes

- name: Ensure app user has a .profile
  file: path="{{ venv_home }}/.profile" state=touch owner={{ venv_user }} group={{ venv_user }} mode=0660

- name: Ensure app user has a .cifrc
  template: src=cifrc.j2 dest="{{ venv_home }}/.cifrc" owner={{ venv_user }} group={{ venv_user }} mode=0660

- name: Ensure .cifrc is linked to .profile
  lineinfile: dest="{{ venv_home }}/.profile" line=". ~/.cifrc"