---
# tasks file for python27
- name: Add python repo
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'
- name: Install pip
  apt: name=python-pip
- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python2.7
    - build-essential
    - python-support
    - python-pytest
    - python-pip
