---
# tasks file for bearded-avenger-dev
- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - virtualenvwrapper
    - git
    - build-essential
    - python-support
    - python-pytest
    - python-pip
    - python-virtualenv
- name: setup virtualenv
  shell: /usr/bin/virtualenv /home/vagrant/.virtualenvs/cif
  sudo_user: vagrant
- name: update pip
  shell: /home/vagrant/.virtualenvs/cif/bin/pip install pip --upgrade
  sudo_user: vagrant
- name: setup deps
  shell: /home/vagrant/.virtualenvs/cif/bin/pip install -r /vagrant/requirements.txt
  sudo_user: vagrant
- name: setup env
  shell: /home/vagrant/.virtualenvs/cif/bin/python /vagrant/setup.py develop
  sudo_user: vagrant

